import { BookOpen, Linkedin, Mail, ShieldCheck } from 'lucide-react';
import Link from 'next/link';

const columns: ReadonlyArray<{ title: string; links: ReadonlyArray<readonly [string, string]> }> = [
  { title: 'Product', links: [['/product', 'Platform overview'], ['/invoicing', 'Invoicing'], ['/accounting', 'Accounting'], ['/ai', 'RetailBooks AI']] },
  { title: 'Solutions', links: [['/industries', 'Industries'], ['/industries/retail', 'Retail'], ['/industries/ecommerce', 'E-commerce'], ['/industries/agencies', 'Agencies']] },
  { title: 'Company', links: [['/customers', 'Customer stories'], ['/security', 'Security'], ['/contact', 'Contact sales'], ['/login', 'Sign in']] },
];
export function SiteFooter() { return <footer className="mk-footer"><div className="mk-footer__cta"><div><p className="mk-kicker">Ready when you are</p><h2>Make room for the work that moves your business forward.</h2></div><Link className="mk-button mk-button--light" href="/signup">Start with RetailBooks</Link></div><div className="mk-footer__grid"><div className="mk-footer__brand"><Link className="mk-brand mk-brand--footer" href="/"><span><BookOpen aria-hidden="true" /></span><strong>RetailBooks</strong></Link><p>Clearer books, calmer decisions, and a capable AI partner when you need one.</p><div><a href="mailto:hello@retailbooks.example" aria-label="Email RetailBooks"><Mail /></a><a href="#" aria-label="RetailBooks on LinkedIn"><Linkedin /></a></div></div>{columns.map(column => <div key={column.title}><h3>{column.title}</h3><ul>{column.links.map(([href, label]) => <li key={href}><Link href={href}>{label}</Link></li>)}</ul></div>)}<div className="mk-footer__secure"><ShieldCheck aria-hidden="true" /><strong>Designed for responsible financial work.</strong><p>Data is encrypted in transit and at rest. Security controls grow with your business.</p><Link href="/security">Our security approach →</Link></div></div><div className="mk-footer__legal"><span>© {new Date().getFullYear()} RetailBooks</span><span>Privacy · Terms · Accessibility</span></div></footer>; }
