/**
 * Stable, machine-readable permission keys.
 *
 * Scoped only to endpoints that exist today, plus the specification's forward-looking keys that
 * name a capability without yet having an enforcement point (`accounts.opening_balances.manage`,
 * `journals.approve`, `security.mfa.manage`) -- a future module wires its `@RequirePermission`
 * decorator to the key that already exists here rather than inventing a new one.
 */
export const PERMISSION_KEYS = [
  'organization.view',
  'organization.update',
  'organization.delete',
  'organization.finalize',
  'organization.transfer_ownership',
  'members.view',
  'members.invite',
  'members.update',
  'members.remove',
  'members.resend_invite',
  'invitations.view',
  'invitations.revoke',
  'roles.view',
  'roles.create',
  'roles.update',
  'roles.delete',
  'roles.assign',
  'roles.manage',
  'settings.localization.manage',
  'settings.currency.manage',
  'settings.tax.manage',
  'settings.fiscal.manage',
  'settings.numbering.manage',
  'settings.accounting.manage',
  'periods.view',
  'periods.manage',
  'periods.close',
  'periods.unlock',
  'numbering.view',
  'numbering.manage',
  'accounts.view',
  'accounts.create',
  'accounts.update',
  'accounts.deactivate',
  'accounts.opening_balances.manage',
  'journals.view',
  'journals.create',
  'journals.post',
  'journals.reverse',
  'journals.approve',
  'journals.recurring.view',
  'journals.recurring.manage',
  'reports.view',
  'tax.codes.view',
  'tax.codes.manage',
  'audit.view',
  'audit.export',
  'security.view',
  'security.sessions.manage',
  'security.mfa.manage',
  'customers.view',
  'customers.manage',
  'customers.currency_override',
  'catalog.view',
  'catalog.manage',
  'sales.invoices.view',
  'sales.invoices.manage',
  'sales.invoices.issue',
  'sales.invoices.void',
  'sales.invoices.revenue_account_override',
  'sales.payments.view',
  'sales.payments.record',
  'sales.payments.allocate',
  'sales.credit_notes.view',
  'sales.credit_notes.manage',
  'sales.credit_notes.issue',
  'sales.credit_notes.void',
  'sales.credit_notes.allocate',
  'sales.credit_notes.refund',
  'sales.quotes.view',
  'sales.quotes.manage',
  'sales.quotes.approve',
  'sales.quotes.convert',
  'sales.orders.view',
  'sales.orders.manage',
  'sales.orders.approve',
  'sales.orders.convert',
  'sales.documents.send',
  'sales.recurring_invoices.view',
  'sales.recurring_invoices.manage',
  'sales.statements.view',
  'vendors.view',
  'vendors.manage',
  'vendors.currency_override',
  'purchases.orders.view',
  'purchases.orders.manage',
  'purchases.orders.approve',
  'purchases.orders.issue',
  'purchases.bills.view',
  'purchases.bills.manage',
  'purchases.bills.issue',
  'purchases.bills.void',
  'purchases.expenses.view',
  'purchases.expenses.manage',
  'purchases.expenses.approve',
  'purchases.expenses.post',
  'purchases.expenses.void',
  'purchases.expense_categories.view',
  'purchases.expense_categories.manage',
  'purchases.vendor_credits.view',
  'purchases.vendor_credits.manage',
  'purchases.vendor_credits.issue',
  'purchases.vendor_credits.void',
  'purchases.vendor_credits.allocate',
  'purchases.payments_made.view',
  'purchases.payments_made.record',
  'purchases.payments_made.allocate',
  'purchases.recurring_bills.view',
  'purchases.recurring_bills.manage',
  'purchases.recurring_expenses.view',
  'purchases.recurring_expenses.manage',
  'banking.accounts.view',
  'banking.accounts.manage',
  'banking.transactions.view',
  'banking.transactions.manage',
  'banking.rules.view',
  'banking.rules.manage',
  'banking.transfers.view',
  'banking.transfers.manage',
  'banking.reconciliations.view',
  'banking.reconciliations.manage',
  'banking.reconciliations.reopen',
] as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[number];

export interface PermissionDefinition {
  readonly key: PermissionKey;
  readonly label: string;
  readonly description: string;
  readonly group:
    | 'Organization'
    | 'Members'
    | 'Invitations'
    | 'Roles'
    | 'Settings'
    | 'Periods'
    | 'Numbering'
    | 'Accounts'
    | 'Journals'
    | 'Reports'
    | 'Tax'
    | 'Audit'
    | 'Security'
    | 'Sales'
    | 'Purchases'
    | 'Banking';
  /**
   * Permanently OWNER-only. No role -- system or custom -- can hold a protected key; there is no
   * grant path for it anywhere, which is the entire privilege-escalation defence.
   */
  readonly protected: boolean;
}

export const PERMISSION_CATALOG: readonly PermissionDefinition[] = Object.freeze([
  {
    key: 'organization.view',
    label: 'View organization profile',
    description: 'See legal, jurisdiction, accounting, tax, and numbering settings.',
    group: 'Organization',
    protected: false,
  },
  {
    key: 'organization.update',
    label: 'Edit organization profile',
    description: "Change the organization's settings.",
    group: 'Organization',
    protected: false,
  },
  {
    key: 'organization.delete',
    label: 'Delete organization',
    description: 'Permanently delete this organization and its data.',
    group: 'Organization',
    protected: true,
  },
  {
    key: 'organization.finalize',
    label: 'Finalize onboarding',
    description: 'Activate the organization once setup is complete.',
    group: 'Organization',
    protected: true,
  },
  {
    key: 'organization.transfer_ownership',
    label: 'Transfer ownership',
    description: 'Make another member the organization owner.',
    group: 'Organization',
    protected: true,
  },
  {
    key: 'members.view',
    label: 'View members',
    description: 'See who belongs to this organization and their role.',
    group: 'Members',
    protected: false,
  },
  {
    key: 'members.invite',
    label: 'Invite members',
    description: 'Send invitations to join this organization.',
    group: 'Members',
    protected: false,
  },
  {
    key: 'members.update',
    label: 'Change member roles',
    description: "Change a member's role, or suspend/reactivate them.",
    group: 'Members',
    protected: false,
  },
  {
    key: 'members.remove',
    label: 'Remove members',
    description: 'Remove a member from this organization.',
    group: 'Members',
    protected: false,
  },
  {
    key: 'members.resend_invite',
    label: 'Resend invitations',
    description: 'Send a pending invitation again with a fresh link.',
    group: 'Members',
    protected: false,
  },
  {
    key: 'invitations.view',
    label: 'View invitations',
    description: 'See pending invitations.',
    group: 'Invitations',
    protected: false,
  },
  {
    key: 'invitations.revoke',
    label: 'Revoke invitations',
    description: 'Withdraw a pending invitation.',
    group: 'Invitations',
    protected: false,
  },
  {
    key: 'roles.view',
    label: 'View roles & permissions',
    description: 'See the roles defined for this organization and what each can do.',
    group: 'Roles',
    protected: false,
  },
  {
    key: 'roles.create',
    label: 'Create custom roles',
    description: 'Define a new role with its own permission set.',
    group: 'Roles',
    protected: false,
  },
  {
    key: 'roles.update',
    label: 'Rename custom roles',
    description: "Change a custom role's name or description.",
    group: 'Roles',
    protected: false,
  },
  {
    key: 'roles.delete',
    label: 'Delete custom roles',
    description: 'Remove a custom role that no member currently holds.',
    group: 'Roles',
    protected: false,
  },
  {
    key: 'roles.assign',
    label: 'Assign roles',
    description: 'Assign any non-owner role to a member.',
    group: 'Roles',
    protected: false,
  },
  {
    key: 'roles.manage',
    label: 'Manage role permissions',
    description: 'Change which permissions a role holds.',
    group: 'Roles',
    protected: true,
  },
  {
    key: 'settings.localization.manage',
    label: 'Manage localization',
    description: 'Change locale, time zone, and date-format defaults.',
    group: 'Settings',
    protected: false,
  },
  {
    key: 'settings.currency.manage',
    label: 'Manage currencies',
    description: 'Enable currencies and manage exchange rates.',
    group: 'Settings',
    protected: false,
  },
  {
    key: 'settings.tax.manage',
    label: 'Manage tax settings',
    description: 'Change tax registration and default tax behavior.',
    group: 'Settings',
    protected: false,
  },
  {
    key: 'settings.fiscal.manage',
    label: 'Manage fiscal settings',
    description: "Change the organization's fiscal-year structure.",
    group: 'Settings',
    protected: false,
  },
  {
    key: 'settings.numbering.manage',
    label: 'Manage numbering settings',
    description: 'Change document numbering defaults at the organization level.',
    group: 'Settings',
    protected: false,
  },
  {
    key: 'settings.accounting.manage',
    label: 'Manage accounting settings',
    description: 'Change accounting basis and chart-of-accounts defaults.',
    group: 'Settings',
    protected: false,
  },
  {
    key: 'periods.view',
    label: 'View fiscal periods',
    description: 'See fiscal years, periods, and lock status.',
    group: 'Periods',
    protected: false,
  },
  {
    key: 'periods.manage',
    label: 'Create fiscal years',
    description: 'Generate fiscal years and their accounting periods.',
    group: 'Periods',
    protected: false,
  },
  {
    key: 'periods.close',
    label: 'Close and lock periods',
    description: 'Close open periods and lock closed periods against posting.',
    group: 'Periods',
    protected: false,
  },
  {
    key: 'periods.unlock',
    label: 'Unlock and reopen periods',
    description: 'Unlock locked periods and reopen closed periods for correction workflows.',
    group: 'Periods',
    protected: false,
  },
  {
    key: 'numbering.view',
    label: 'View document numbering',
    description: 'See document numbering configuration and current counters.',
    group: 'Numbering',
    protected: false,
  },
  {
    key: 'numbering.manage',
    label: 'Manage document numbering',
    description: 'Change document numbering prefixes, reset cadence, padding, and next numbers.',
    group: 'Numbering',
    protected: false,
  },
  {
    key: 'accounts.view',
    label: 'View chart of accounts',
    description: 'See accounts, account status, and balances.',
    group: 'Accounts',
    protected: false,
  },
  {
    key: 'accounts.create',
    label: 'Create accounts',
    description: 'Add new accounts to the chart of accounts.',
    group: 'Accounts',
    protected: false,
  },
  {
    key: 'accounts.update',
    label: 'Edit accounts',
    description: 'Change account names, types, and normal balances.',
    group: 'Accounts',
    protected: false,
  },
  {
    key: 'accounts.deactivate',
    label: 'Archive accounts',
    description: 'Archive an account so it can no longer be selected.',
    group: 'Accounts',
    protected: false,
  },
  {
    key: 'accounts.opening_balances.manage',
    label: 'Manage opening balances',
    description: 'Set or change account opening balances.',
    group: 'Accounts',
    protected: false,
  },
  {
    key: 'journals.view',
    label: 'View journals',
    description: 'See draft, posted, and reversed journals.',
    group: 'Journals',
    protected: false,
  },
  {
    key: 'journals.create',
    label: 'Create journal drafts',
    description: 'Create and edit draft journals.',
    group: 'Journals',
    protected: false,
  },
  {
    key: 'journals.post',
    label: 'Post journals',
    description: 'Post balanced journals into open fiscal periods.',
    group: 'Journals',
    protected: false,
  },
  {
    key: 'journals.reverse',
    label: 'Reverse posted journals',
    description: 'Create explicit reversal journals for posted entries.',
    group: 'Journals',
    protected: false,
  },
  {
    key: 'journals.approve',
    label: 'Approve journals',
    description: 'Approve a draft journal before it can be posted.',
    group: 'Journals',
    protected: false,
  },
  {
    key: 'journals.recurring.view',
    label: 'View recurring journals',
    description: 'See recurring journal templates and their schedules.',
    group: 'Journals',
    protected: false,
  },
  {
    key: 'journals.recurring.manage',
    label: 'Manage recurring journals',
    description: 'Create, edit, and run recurring journal templates.',
    group: 'Journals',
    protected: false,
  },
  {
    key: 'reports.view',
    label: 'View ledger reports',
    description: 'See trial balance and account-ledger inquiries.',
    group: 'Reports',
    protected: false,
  },
  {
    key: 'tax.codes.view',
    label: 'View tax codes',
    description: 'See tax codes, effective-dated rates, and recoverability settings.',
    group: 'Tax',
    protected: false,
  },
  {
    key: 'tax.codes.manage',
    label: 'Manage tax codes',
    description: 'Create, edit, and archive tax codes, and add effective-dated rates.',
    group: 'Tax',
    protected: false,
  },
  {
    key: 'audit.view',
    label: 'View audit log',
    description:
      'See the chronological record of security-relevant actions across this organization.',
    group: 'Audit',
    protected: false,
  },
  {
    key: 'audit.export',
    label: 'Export audit log',
    description: 'Download the audit and security event history as CSV.',
    group: 'Audit',
    protected: false,
  },
  {
    key: 'security.view',
    label: 'View security settings',
    description: "See the organization's session and security policy settings.",
    group: 'Security',
    protected: false,
  },
  {
    key: 'security.sessions.manage',
    label: 'Manage sessions',
    description: 'Revoke sessions belonging to other members.',
    group: 'Security',
    protected: false,
  },
  {
    key: 'security.mfa.manage',
    label: 'Manage MFA policy',
    description: 'Change multi-factor authentication requirements for this organization.',
    group: 'Security',
    protected: false,
  },
  {
    key: 'customers.view',
    label: 'View customers',
    description: 'See customer records and their contact and billing details.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'customers.manage',
    label: 'Manage customers',
    description: 'Create, edit, and deactivate customer records.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'customers.currency_override',
    label: 'Override customer currency',
    description:
      "Set a customer's currency to something other than the organization's base currency.",
    group: 'Sales',
    protected: false,
  },
  {
    key: 'catalog.view',
    label: 'View catalog',
    description: 'See items, services, units, and categories.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'catalog.manage',
    label: 'Manage catalog',
    description: 'Create, edit, and deactivate items, services, units, and categories.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.invoices.view',
    label: 'View invoices',
    description: 'See draft, issued, and voided invoices.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.invoices.manage',
    label: 'Manage invoice drafts',
    description: 'Create and edit draft invoices.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.invoices.issue',
    label: 'Issue invoices',
    description: 'Post a draft invoice, allocating its number and its AR/revenue/tax journal.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.invoices.void',
    label: 'Void invoices',
    description: 'Reverse an issued invoice that has no payments applied.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.invoices.revenue_account_override',
    label: 'Override invoice revenue account',
    description:
      "Set an invoice line's revenue account to something other than the item's default.",
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.payments.view',
    label: 'View payments',
    description: 'See recorded customer payments and their allocations.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.payments.record',
    label: 'Record payments',
    description: 'Record a customer payment, posting it to the ledger immediately.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.payments.allocate',
    label: 'Allocate payments',
    description: "Apply a recorded payment against one or more of a customer's open invoices.",
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.credit_notes.view',
    label: 'View credit notes',
    description: 'See draft, issued, applied, refunded, and voided credit notes.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.credit_notes.manage',
    label: 'Manage credit note drafts',
    description: 'Create and edit draft credit notes.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.credit_notes.issue',
    label: 'Issue credit notes',
    description:
      'Post a draft credit note, allocating its number and its revenue/tax reversal journal.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.credit_notes.void',
    label: 'Void credit notes',
    description: 'Reverse an issued credit note that has no allocations or refunds applied.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.credit_notes.allocate',
    label: 'Allocate credit notes',
    description: "Apply a credit note's remaining balance against one or more open invoices.",
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.credit_notes.refund',
    label: 'Refund credit notes',
    description: "Pay out a credit note's remaining balance to the customer in cash.",
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.quotes.view',
    label: 'View quotes',
    description: 'See draft, sent, and resolved sales quotes.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.quotes.manage',
    label: 'Manage quotes',
    description: 'Create, edit, submit, send, accept, decline, and expire quotes.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.quotes.approve',
    label: 'Approve quotes',
    description: 'Approve a quote pending approval.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.quotes.convert',
    label: 'Convert quotes',
    description: 'Convert an accepted quote into a draft invoice.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.orders.view',
    label: 'View sales orders',
    description: 'See draft, confirmed, and fulfilled sales orders.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.orders.manage',
    label: 'Manage sales orders',
    description: 'Create, edit, confirm, fulfill, and cancel sales orders.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.orders.approve',
    label: 'Approve sales orders',
    description: 'Approve a draft sales order.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.orders.convert',
    label: 'Convert sales orders',
    description: 'Convert a confirmed or fulfilled sales order into a draft invoice.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.documents.send',
    label: 'Send documents',
    description: 'Email an invoice, credit note, or quote as a PDF to the customer.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.recurring_invoices.view',
    label: 'View recurring invoices',
    description: 'See recurring invoice templates.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.recurring_invoices.manage',
    label: 'Manage recurring invoices',
    description: 'Create, edit, (de)activate recurring invoice templates, and run due templates.',
    group: 'Sales',
    protected: false,
  },
  {
    key: 'sales.statements.view',
    label: 'View customer statements',
    description: "See a customer's invoice, payment, and credit-note activity and running balance.",
    group: 'Sales',
    protected: false,
  },
  {
    key: 'vendors.view',
    label: 'View vendors',
    description: 'See vendor records and their contact and payment details.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'vendors.manage',
    label: 'Manage vendors',
    description: 'Create, edit, and deactivate vendor records.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'vendors.currency_override',
    label: 'Override vendor currency',
    description:
      "Set a vendor's currency to something other than the organization's base currency.",
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.orders.view',
    label: 'View purchase orders',
    description: 'See draft, approved, issued, and closed purchase orders.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.orders.manage',
    label: 'Manage purchase orders',
    description: 'Create, edit, record receipts on, close, and cancel purchase orders.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.orders.approve',
    label: 'Approve purchase orders',
    description: 'Approve a draft purchase order.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.orders.issue',
    label: 'Issue purchase orders',
    description: 'Send an approved purchase order to the vendor, allocating its number.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.bills.view',
    label: 'View bills',
    description: 'See draft, issued, and voided bills.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.bills.manage',
    label: 'Manage bill drafts',
    description: 'Create and edit draft bills, and upload their attachments.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.bills.issue',
    label: 'Issue bills',
    description: 'Post a draft bill, allocating its number and its AP/expense/tax journal.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.bills.void',
    label: 'Void bills',
    description: 'Reverse an issued bill that has no payments applied.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.expenses.view',
    label: 'View expenses',
    description: 'See draft, pending, approved, posted, and voided expenses.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.expenses.manage',
    label: 'Manage expense drafts',
    description: 'Create, edit, submit, and cancel expenses, and upload their receipts.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.expenses.approve',
    label: 'Approve expenses',
    description: 'Approve an expense pending approval.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.expenses.post',
    label: 'Post expenses',
    description: 'Post an expense, allocating its number and its expense/tax journal.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.expenses.void',
    label: 'Void expenses',
    description: 'Reverse a posted expense.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.expense_categories.view',
    label: 'View expense categories',
    description: 'See expense categories and their mapped accounts.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.expense_categories.manage',
    label: 'Manage expense categories',
    description: 'Create, edit, and deactivate expense categories.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.vendor_credits.view',
    label: 'View vendor credits',
    description: 'See draft, issued, applied, and voided vendor credits.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.vendor_credits.manage',
    label: 'Manage vendor credit drafts',
    description: 'Create and edit draft vendor credits.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.vendor_credits.issue',
    label: 'Issue vendor credits',
    description:
      'Post a draft vendor credit, allocating its number and its expense/tax reversal journal.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.vendor_credits.void',
    label: 'Void vendor credits',
    description: 'Reverse an issued vendor credit that has no allocations applied.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.vendor_credits.allocate',
    label: 'Allocate vendor credits',
    description: "Apply a vendor credit's remaining balance against one or more open bills.",
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.payments_made.view',
    label: 'View payments made',
    description: 'See recorded vendor payments and their allocations.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.payments_made.record',
    label: 'Record payments made',
    description: 'Record a vendor payment, posting it to the ledger immediately.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.payments_made.allocate',
    label: 'Allocate payments made',
    description: "Apply a recorded payment against one or more of a vendor's open bills.",
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.recurring_bills.view',
    label: 'View recurring bills',
    description: 'See recurring bill templates.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.recurring_bills.manage',
    label: 'Manage recurring bills',
    description: 'Create, edit, (de)activate recurring bill templates, and run due templates.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.recurring_expenses.view',
    label: 'View recurring expenses',
    description: 'See recurring expense templates.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'purchases.recurring_expenses.manage',
    label: 'Manage recurring expenses',
    description: 'Create, edit, (de)activate recurring expense templates, and run due templates.',
    group: 'Purchases',
    protected: false,
  },
  {
    key: 'banking.accounts.view',
    label: 'View financial accounts',
    description: 'See bank, cash, and credit-card accounts and their GL mapping.',
    group: 'Banking',
    protected: false,
  },
  {
    key: 'banking.accounts.manage',
    label: 'Manage financial accounts',
    description: 'Create, edit, and (de)activate financial accounts.',
    group: 'Banking',
    protected: false,
  },
  {
    key: 'banking.transactions.view',
    label: 'View bank transactions',
    description: 'See imported bank transactions and their match/categorize status.',
    group: 'Banking',
    protected: false,
  },
  {
    key: 'banking.transactions.manage',
    label: 'Manage bank transactions',
    description: 'Import statements, and categorize, split, match, unmatch, and exclude transactions.',
    group: 'Banking',
    protected: false,
  },
  {
    key: 'banking.rules.view',
    label: 'View bank rules',
    description: 'See bank rules and their conditions and suggestions.',
    group: 'Banking',
    protected: false,
  },
  {
    key: 'banking.rules.manage',
    label: 'Manage bank rules',
    description: 'Create, edit, and (de)activate bank rules.',
    group: 'Banking',
    protected: false,
  },
  {
    key: 'banking.transfers.view',
    label: 'View transfers',
    description: 'See transfers between financial accounts.',
    group: 'Banking',
    protected: false,
  },
  {
    key: 'banking.transfers.manage',
    label: 'Manage transfers',
    description: 'Post and void transfers between financial accounts.',
    group: 'Banking',
    protected: false,
  },
  {
    key: 'banking.reconciliations.view',
    label: 'View reconciliations',
    description: 'See reconciliations and their cleared transactions.',
    group: 'Banking',
    protected: false,
  },
  {
    key: 'banking.reconciliations.manage',
    label: 'Manage reconciliations',
    description: 'Start a reconciliation, mark transactions cleared, and complete it.',
    group: 'Banking',
    protected: false,
  },
  {
    key: 'banking.reconciliations.reopen',
    label: 'Reopen reconciliations',
    description: 'Reopen a completed reconciliation with a recorded reason.',
    group: 'Banking',
    protected: false,
  },
]);

export const PROTECTED_PERMISSION_KEYS: ReadonlySet<PermissionKey> = new Set(
  PERMISSION_CATALOG.filter((permission) => permission.protected).map(
    (permission) => permission.key,
  ),
);

export function isPermissionKey(value: string): value is PermissionKey {
  return (PERMISSION_KEYS as readonly string[]).includes(value);
}
